name: Continuous Integration

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: CMake generate buildsystem
        run: mkdir build && cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest
